### ISSUE TITLE
PDF合并报错

### ISSUE THREAD

**Issue by huoxianribao** [kevin2li/PDF-Guru#14]
: Traceback (most recent call last): File "merge.py", line 68, in merge_pdf File "fitz\fitz.py", line 4629, in save RuntimeError: cannot remove file 'E:\ppddfff\1\1': Permission denied

尝试使用管理员模式运行

**Comment by huoxianribao** [comment]
解决了，输出路径那一块得写输出文件名，第一次用。感觉缺少引导提示，我就单纯得写了一个输出路径（），顺便希望作者能做一下批量虚拟打印出来的pdf，有大量含有特殊字体的doc文档转pdf的需求
