### ISSUE TITLE
PDF OCR显示连接服务器超时

### ISSUE THREAD

**Issue by pheotry** [kevin2li/PDF-Guru#53]
又过了一会儿报这个错误
```txt
Traceback (most recent call last):
  File "guru_server\main.py", line 13, in <module>
  File "C:\Users\sand\AppData\Local\Temp\_MEI97642\guru_server\video_toolbox\__init__.py", line 11, in <module video_toolbox>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\sand\AppData\Local\Temp\_MEI97642\guru_server\video_toolbox\my_player\__init__.py", line 8, in <module video_toolbox.my_player>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\sand\AppData\Local\Temp\_MEI97642\guru_server\video_toolbox\my_player\potplayer_control.py", line 15, in <module video_toolbox.my_player.potplayer_control>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "win32com\client\__init__.py", line 14, in <module>
    from . import dynamic, gencache
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "win32com\client\gencache.py", line 764, in <module>
    __init__()
  File "win32com\client\gencache.py", line 63, in __init__
    _LoadDicts()
  File "win32com\client\gencache.py", line 122, in _LoadDicts
    version = p.load()
_pickle.UnpicklingError: invalid load key, '\x00'.
```

**Comment by pheotry** [comment]
这是要自己再装个python环境吗

**Comment by kevin2li** [comment]
软件重装下，然后把安装目录添加到杀毒软件信任区
