### ISSUE TITLE
运行windows-cli版程序报错

### ISSUE THREAD

**Issue by bigmouse0001** [kevin2li/PDF-Guru#9]
Traceback (most recent call last):
  File "pdf.py", line 192, in <module>
  File "pdf.py", line 43, in main
AttributeError: 'Namespace' object has no attribute 'which'

**Comment by kevin2li** [comment]
你用./pdf.exe -h 查看下帮助信息

**Comment by wf3699** [comment]
PDF拆分功能 
处理失败！
: 命令执行失败!: exec: "C:\\Users\\Mac\\Downloads\\pdf-guru-windows-amd64-1.0.12\\pdf.exe": file does not exist

pdf.exe -h提示
Traceback (most recent call last):
  File "pdf.py", line 192, in <module>
  File "pdf.py", line 41, in main
  File "argparse.py", line 1768, in parse_args
  File "argparse.py", line 1800, in parse_known_args
  File "argparse.py", line 2006, in _parse_known_args
  File "argparse.py", line 1946, in consume_optional
  File "argparse.py", line 1874, in take_action
  File "argparse.py", line 1044, in __call__
  File "argparse.py", line 2494, in print_help
  File "argparse.py", line 2500, in _print_message
AttributeError: 'NoneType' object has no attribute 'write'
